"""Shipped git metadata: `.git/config` command keys and active `.git/hooks`.

A local directory or an archive can ship its own `.git`; any git command the user
(or a tool such as an IDE, prompt or scanner) runs there honours that config:
core.fsmonitor runs on `git status`, core.pager/editor, diff/filter drivers and
`!` aliases run on everyday commands, and executable hooks run on commit/checkout.
Parsed statically here; git itself is never run against the target.
"""
from __future__ import annotations

import os
import re
import stat
from typing import Iterator

from core import HIGH, INFO, Finding, Repo, clean, code_lines, finding
from vcs_hooks import DISABLED_HOOKS, GIT_HOOKS, hook_reason, scan_hook_dir

MAX_INCLUDE_DEPTH = 10
SECTION = re.compile(r'^\[\s*([A-Za-z0-9.-]+)(?:\s+"((?:[^"\\]|\\.)*)")?\s*\]\s*(.*)$')
KEY_VALUE = re.compile(r"^([A-Za-z][A-Za-z0-9-]*)\s*(?:=\s*(.*))?$")
BOOLEAN = {"true", "false", "yes", "no", "on", "off", "1", "0", ""}
# key (section.key, subsection removed) -> what triggers it
COMMAND_KEYS = {
    "core.fsmonitor": "runs on git status",
    "core.pager": "runs as git pager",
    "core.editor": "runs as git editor",
    "sequence.editor": "runs on git rebase",
    "core.sshcommand": "runs on fetch/push",
    "core.gitproxy": "runs on fetch",
    "core.askpass": "runs on authentication",
    "diff.external": "runs on git diff",
    "gpg.program": "runs on signing/verification",
    "gpg.ssh.program": "runs on signing/verification",
    "web.browser": "runs on git help/web",
    "credential.helper": "runs on authentication",
    "filter.clean": "runs on git add/status",
    "filter.smudge": "runs on checkout",
    "filter.process": "runs on checkout/add",
    "diff.textconv": "runs on git diff/log",
    "diff.command": "runs on git diff",
    "merge.driver": "runs on merge",
    "remote.uploadpack": "runs on fetch",
    "remote.receivepack": "runs on push",
    "browser.cmd": "runs on git help/web",
}
# Values that are well-known programs (a developer's own checkout, git lfs install)
BENIGN_PROGRAM = re.compile(
    r"^\s*(vim?|nvim|nano|emacs(client)?|code\s+(--wait|-w)|subl\s+(-w|--wait)|mate\s+-w"
    r"|less(\s+-[A-Za-z]+)*|more|cat|delta|diff-so-fancy(\s*\|\s*less.*)?|bat|most|"
    r"git-lfs\s+(clean|smudge|filter-process)(\s+--\s+%f)?|gpg2?|ssh-keygen|ssh)\s*$")
GENERATED_HOOK = re.compile(
    r"File generated by pre-commit|husky\.sh|_/husky|lefthook|git lfs |command -v git-lfs"
    r"|simple-git-hooks|overcommit|git-secrets|talisman|commitizen")


def parse_config(text: str) -> Iterator[tuple[str, str, str]]:
    """(section, subsection, key=value...) triples: yields (name, sub, value) per key.

    Names are lowercased (git compares sections and keys case-insensitively).
    """
    section, sub = "", ""
    joined: list[str] = []
    for raw in text.splitlines():
        if raw.rstrip().endswith("\\") and not raw.rstrip().endswith("\\\\"):
            joined.append(raw.rstrip()[:-1])
            continue
        line = ("".join(joined) + raw).strip()
        joined = []
        while line.startswith("["):
            match = SECTION.match(line)
            if not match:
                break
            section, sub = match.group(1).lower(), match.group(2) or ""
            if match.group(2) is None and "." in section:  # [section.sub] legacy form
                section, sub = section.split(".", 1)
            line = match.group(3).strip()
        if not line or line.startswith(("#", ";", "[")):
            continue
        match = KEY_VALUE.match(line)
        if match and section:
            yield f"{section}.{match.group(1).lower()}", sub, _value(match.group(2) or "")


def _value(raw: str) -> str:
    """Config value: quotes removed, unquoted inline comment dropped."""
    out, quoted, i = [], False, 0
    while i < len(raw):
        char = raw[i]
        if char == "\\" and i + 1 < len(raw):
            out.append({"n": "\n", "t": "\t"}.get(raw[i + 1], raw[i + 1]))
            i += 2
            continue
        if char == '"':
            quoted = not quoted
        elif char in "#;" and not quoted:
            break
        else:
            out.append(char)
        i += 1
    return "".join(out).strip()


def key_verdict(key: str, value: str) -> tuple[str, str] | None:
    """(level, reason) for a command-running config key, else None.

    key is `section.name` with any subsection removed (filter "x".clean -> filter.clean).
    """
    if key.startswith("alias."):
        return (HIGH, f"shell alias (runs on git {clean(key[6:])[:30]})") \
            if value.startswith("!") else None
    why = COMMAND_KEYS.get(key)
    if not why or not value:
        return None
    if key == "core.fsmonitor" and value.lower() in BOOLEAN:
        return None  # built-in fsmonitor daemon
    if key == "credential.helper" and not value.startswith(("!", "/")) and " " not in value:
        return INFO, f"credential helper git-credential-{clean(value)[:30]}"
    if BENIGN_PROGRAM.match(value):
        return INFO, f"{key} {why}"
    return HIGH, f"{key} {why}"


def in_repo(repo: Repo, path: str) -> tuple[str | None, bool]:
    """(path to read, ok): symlinked paths followed only while they stay in the repo."""
    if not os.path.islink(path):
        return path, True
    real = repo.resolve_inside(path)
    return (real, True) if real else (None, False)


def git_dir(repo: Repo) -> tuple[str | None, list[Finding]]:
    """The target's git directory (a `.git` dir, or a `gitdir:` file kept in-repo)."""
    dot_git = os.path.join(repo.root, ".git")
    if not os.path.lexists(dot_git):
        return None, []
    if os.path.islink(dot_git):
        target = repo.resolve_inside(dot_git)
        if not target or not os.path.isdir(target):
            return None, [finding(HIGH, ".git", "is a symlink leaving the repo (or dangling)")]
        return target, []
    if os.path.isdir(dot_git):
        return dot_git, []
    try:
        text = repo.read_text(dot_git).strip()
    except OSError:
        return None, []
    if not text.startswith("gitdir:"):
        return None, []
    path = os.path.join(repo.root, text[len("gitdir:"):].strip())
    target = repo.resolve_inside(path)
    if target and os.path.isdir(target):
        return target, []
    return None, [finding(INFO, ".git", "gitdir file points outside the target (not analysed)",
                          text)]


def scan_config(repo: Repo, path: str, depth: int, seen: set[str]) -> Iterator[Finding]:
    """Command keys of one config file; in-repo include/includeIf paths followed."""
    if path in seen or depth > MAX_INCLUDE_DEPTH:
        return
    seen.add(path)
    rel = repo.rel(path)
    path, ok = in_repo(repo, path)
    if not ok:
        yield finding(HIGH, rel, "git config is a symlink leaving the repo (or dangling)")
        return
    try:
        text = repo.read_text(path)
    except OSError:
        return
    for key, sub, value in parse_config(text.lstrip("\ufeff")):  # git skips a UTF-8 BOM
        if key in ("include.path", "includeif.path"):
            yield from _include(repo, path, rel, value, depth, seen)
            continue
        if key == "core.hookspath":
            yield from _hooks_path(repo, rel, value)
            continue
        verdict = key_verdict(key, value)
        if verdict:
            label = f"{key.split('.', 1)[0]} \"{clean(sub)[:30]}\" {key.split('.', 1)[1]}" \
                if sub else key
            yield finding(verdict[0], rel, f"{verdict[1]} [{label}]", value)


def _include(repo: Repo, path: str, rel: str, value: str, depth: int,
             seen: set[str]) -> Iterator[Finding]:
    if not value:
        return
    target = repo.inside(os.path.join(os.path.dirname(path), value)) \
        if not value.startswith("~") else None
    real = repo.resolve_inside(target) if target else None
    if real and os.path.isfile(real):
        yield finding(INFO, rel, "includes config", repo.rel(real))
        yield from scan_config(repo, real, depth + 1, seen)
    else:
        repo.warn(f"{rel}: includes config from outside the target (not analysed): "
                  f"{clean(value)[:80]}")


def _hooks_path(repo: Repo, rel: str, value: str) -> Iterator[Finding]:
    if not value or value in DISABLED_HOOKS:
        return
    expanded = value if os.path.isabs(value) or value.startswith("~") else \
        os.path.join(repo.root, value)
    target = repo.inside(expanded) if not value.startswith("~") else None
    real = repo.resolve_inside(target) if target else None
    if real and os.path.isdir(real):
        yield finding(INFO, rel, "sets core.hooksPath", value)
        yield from scan_hook_dir(repo, real, f"core.hooksPath in {clean(rel)[:40]}")
    else:
        yield finding(HIGH, rel, "core.hooksPath runs hooks from outside the repo", value)


def scan_hooks(repo: Repo, hooks: str) -> Iterator[Finding]:
    """Executable, non-sample hooks in the shipped hooks directory."""
    real, ok = in_repo(repo, hooks)
    if not ok:
        yield finding(HIGH, repo.rel(hooks), "hooks dir is a symlink leaving the repo")
        return
    hooks = real
    try:
        names = sorted(os.listdir(hooks))
    except OSError:
        return
    for name in names:
        if name not in GIT_HOOKS:
            continue  # git only runs known hook names (*.sample never)
        path = os.path.join(hooks, name)
        rel = repo.rel(path)
        if os.path.islink(path):
            real = repo.resolve_inside(path)
            if not real or not os.path.isfile(real):
                yield finding(HIGH, rel, "active git hook is a symlink leaving the repo")
                continue
            repo.warn(f"{rel}: active git hook is a symlink to {repo.rel(real)}")
            path = real
        try:
            mode = os.lstat(path).st_mode
        except OSError:
            continue
        if not stat.S_ISREG(mode) or not mode & 0o111:
            continue  # git skips non-executable hooks
        try:
            text = code_lines(repo.read_text(path))
        except OSError:
            continue
        hit = hook_reason(repo, text, hooks)
        if hit:
            yield finding(HIGH, rel, f"active git hook {hit[0]}", hit[1])
        elif GENERATED_HOOK.search(text):
            yield finding(INFO, rel, "active git hook (hook manager)")
        else:
            repo.warn(f"{rel}: active git hook {name} shipped with the target")


def handle_git_dir(repo: Repo) -> Iterator[Finding]:
    """Findings for the target's own git metadata (never runs git)."""
    gdir, found = git_dir(repo)
    yield from found
    if not gdir:
        return
    seen: set[str] = set()
    common, found = common_dir(repo, gdir)
    yield from found
    # Per-worktree config (extensions.worktreeConfig) and the shared config/hooks
    # of a commondir: git reads both, so a shipped .git can hide keys there
    for cfg in (os.path.join(gdir, "config"), os.path.join(gdir, "config.worktree")):
        yield from scan_config(repo, cfg, 0, seen)
    if common and common != gdir:
        for cfg in (os.path.join(common, "config"), os.path.join(common, "config.worktree")):
            yield from scan_config(repo, cfg, 0, seen)
    yield from scan_hooks(repo, os.path.join(common or gdir, "hooks"))


def common_dir(repo: Repo, gdir: str) -> tuple[str | None, list[Finding]]:
    """The `commondir` git shares config and hooks from (kept inside the target)."""
    path = os.path.join(gdir, "commondir")
    if not os.path.lexists(path):
        return gdir, []
    rel = repo.rel(path)
    try:
        value = repo.read_text(path).strip()
    except OSError:
        return gdir, [finding(HIGH, rel, "is not a regular file (symlink or special file)")]
    target = repo.inside(os.path.join(gdir, value)) if value else None
    real = repo.resolve_inside(target) if target else None
    if real and os.path.isdir(real):
        return real, [finding(INFO, rel, "shares config and hooks from", repo.rel(real))]
    return None, [finding(HIGH, rel, "points outside the repo (git would use that config)",
                          value)]
